USE g8delghlzbuijzrh;

CREATE TABLE burgers (
id INTEGER (10) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(100),
devoured BOOLEAN NOT NULL DEFAULT 0,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

SELECT * FROM burgers;